### ISSUE TITLE
Muti event listen, so the function will be run many times.

### ISSUE THREAD

**Issue by wind13** [jimsparkman/RiotControl#25]
When addStore two or more modules, it will cause the RiotControl.on("evtName", fn) the fn will run many( modules.length ) times.

```
var todoStore = new TodoStore() // Create a store instance.
RiotControl.addStore(todoStore)
var otherStore = new OtherStore()
RiotControl.addStore(otherStore)

RiotControl.on("try", function(){
    console.debug("Why tried two times?")
})

RiotControl.trigger("try")
```

**Comment by Ollink** [comment]
Same problem here, issue is also the same as #7  and #9 .
Doesn't seem like it's clear whether this is a bug ( i think so) or intended. 
I'm wondering whether this repo is abandoned, as the owner doesn't  respond to this issue anymore. 
If there are no further updates, it would maybe be better to unlink this from https://github.com/riot/riot .

**Comment by alexbrowne** [comment]
I looked at the code and it links the trigger to every store, so its a multiple of no. of stores it will trigger. I guess if you keep to one store this would not be an issue. Perhaps that is design concept that riotcontrol is suggesting. If you are like myself and use multiple stores, here is a work around (albeit ugly). You can send a stamp so that it only runs once per trigger event on each receiver.

```
var todoStore = new TodoStore() // Create a store instance.
RiotControl.addStore(todoStore)
var otherStore = new OtherStore()
RiotControl.addStore(otherStore)

self.lastStamp = '' // scoped to the trigger
RiotControl.on("try", function(stamp){
   if (self.lastStamp != stamp){
     self.lastStamp = stamp
     console.debug("Only run once rather than once per store")
   }
})

RiotControl.trigger("try", Math.random()*1000)

```

**Comment by opture** [comment]
Its been a few days since last activity here. Adding my comment anyhow.
The stores are the ones registered to listen for the events, not riotcontrol. Riotcontrol passes the event to each and every store, so trigger events on riotcontrol ndbutisten for events in your stores.

var todoStore = new TodoStore() // Create a store instance.
RiotControl.addStore(todoStore)
var otherStore = new OtherStore()
RiotControl.addStore(otherStore)

todoStore.on('try', function(){
 console.log('triggers once')
})
RiotControl.trigger("try", Math.random()*1000)
